## Kaggle Task1 Predicting/estimating the temperature of Trout Lake at depth 10.5 m during Apr 20th, 2018 - Apr 19th, 2019. 

In [28]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [29]:
import warnings
warnings.filterwarnings("ignore")

In [30]:
train = pd.read_csv('Trout_training.csv')

In [31]:
test = pd.read_csv('Trout_testing_features.csv')

In [32]:
type(train.iloc[2].Date_Time)

str

In [33]:
train_sensor = train.pivot(index='Date_Time', columns='Depth_m', values='Water_Temp_C')

In [34]:
features = list(train_sensor.columns)

In [35]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(train_sensor[features])
train_sensor[features]=imp.transform(train_sensor[features])
train_sensor[features]=train_sensor[features].round(3)

In [36]:
train_sensor.head()

Depth_m               1.5    2.5    3.5    4.5    5.5    6.5    7.5    8.5   \
Date_Time                                                                     
2012-04-20 00:00:00  5.257  5.257  5.257  5.205  5.205  5.154  5.231  5.128   
2012-04-20 01:00:00  5.205  5.231  5.231  5.179  5.205  5.154  5.231  5.128   
2012-04-20 02:00:00  5.231  5.231  5.231  5.154  5.179  5.128  5.154  4.973   
2012-04-20 03:00:00  5.205  5.231  5.205  5.154  5.154  5.102  5.128  4.999   
2012-04-20 04:00:00  5.205  5.231  5.154  5.050  5.050  4.999  5.076  4.999   

Depth_m               9.5    10.5   11.5   12.5   14.5   16.5   18.5   20.5  
Date_Time                                                                    
2012-04-20 00:00:00  5.102  5.076  4.792  4.818  4.766  4.792  4.792  4.818  
2012-04-20 01:00:00  5.024  4.999  4.792  4.818  4.766  4.792  4.792  4.792  
2012-04-20 02:00:00  4.895  4.895  4.792  4.792  4.740  4.792  4.792  4.792  
2012-04-20 03:00:00  4.895  4.921  4.766  4.818  4.766  4.792  4.792  4.766  
2012-04-20 04:00:00  4.947  4.973  4.818  4.844  4.792  4.792  4.792  4.766

In [37]:
train_sensor.dropna()
train_sensor.shape

(52515, 16)

In [38]:
test_sensor = test.pivot(index='Date_Time', columns='Depth_m', values='Water_Temp_C')

In [39]:
feature_t = list(test_sensor.columns)

In [40]:
imp2 = SimpleImputer(missing_values=np.nan, strategy='mean')
imp2 = imp2.fit(test_sensor[feature_t])
test_sensor[feature_t]=imp2.transform(test_sensor[feature_t])
test_sensor[feature_t]=test_sensor[feature_t].round(3)

In [41]:
test_sensor.dropna()
test_sensor.shape

(8760, 15)

In [42]:
X = train_sensor[[1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 11.5,
              12.5, 14.5, 16.5, 18.5, 20.5]]
y = train_sensor[[10.5]]

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [44]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_scaled = scaler.fit_transform(X)


In [45]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(X_scaled)

In [46]:
test_sensor_scaled = scaler.transform(test_sensor)

In [47]:
test_poly = poly.fit_transform(test_sensor_scaled)

SVR

In [235]:
from sklearn import svm
#reg = svm.SVR()
#reg.fit(X_train_scaled, y_train)

In [201]:
#reg.score(X_train_scaled, y_train)

In [202]:
#reg.score(X_test_scaled, y_test)

In [203]:
#y_pred_s = reg.predict(X_test_scaled)
#mean_squared_error(y_test,y_pred_s)

#### SVR tune

In [204]:
'''
from sklearn.model_selection import cross_val_score
import operator
scores = {}

for this_gamma in 10**np.linspace(-2, 2, 5):
    for this_C in 10**np.linspace(-2, 2, 5):
        svr = svm.SVR(kernel='rbf', gamma=this_gamma, C=this_C)
        scores[(this_gamma, this_C)] = np.mean(cross_val_score(svr, X_train_scaled, y_train, cv=5))
    
best_gamma, best_C = max(scores.items(), key=operator.itemgetter(1))[0]
svr = svm.SVR(kernel='rbf', gamma=best_gamma, C=best_C).fit(X_train_scaled, y_train)
'''

"\nfrom sklearn.model_selection import cross_val_score\nimport operator\nscores = {}\n\nfor this_gamma in 10**np.linspace(-2, 2, 5):\n    for this_C in 10**np.linspace(-2, 2, 5):\n        svr = svm.SVR(kernel='rbf', gamma=this_gamma, C=this_C)\n        scores[(this_gamma, this_C)] = np.mean(cross_val_score(svr, X_train_scaled, y_train, cv=5))\n    \nbest_gamma, best_C = max(scores.items(), key=operator.itemgetter(1))[0]\nsvr = svm.SVR(kernel='rbf', gamma=best_gamma, C=best_C).fit(X_train_scaled, y_train)\n"

In [205]:
'''
print('Best gamma: {}'.format(best_gamma))
print('Best C: {}'.format(best_C))
print('Training accuracy: {}'.format(svr.score(X_train_scaled, y_train)))
print('Test accuracy: {}'.format(svr.score(X_test_scaled, y_test)))
'''

"\nprint('Best gamma: {}'.format(best_gamma))\nprint('Best C: {}'.format(best_C))\nprint('Training accuracy: {}'.format(svr.score(X_train_scaled, y_train)))\nprint('Test accuracy: {}'.format(svr.score(X_test_scaled, y_test)))\n"

Best gamma: 10.0
Best C: 100.0
Training accuracy: 0.9985229107586874
Test accuracy: 0.9975761121899951

In [ ]:
#svr = svm.SVR(kernel='linear', gamma=10.0, C=100).fit(X_poly, y)

In [207]:
#y_pred_svr = svr.predict(X_test_scaled)
#mean_squared_error(y_test,y_pred_svr)

0.023494567361860202

In [257]:
#svr.score(X_poly, y)

0.9988552302877475

In [209]:
#svr.score(X_test_scaled, y_test)

0.9975761121899951

In [287]:
test_sensor =  test_sensor.drop(columns=['Predict'])

In [262]:
test_predict=svr.predict(test_poly)

In [263]:
test_predict

array([1.47284523, 1.47284523, 1.47258691, ..., 3.69844363, 3.70744998,
       3.70417493])

In [264]:
len(test_predict)

8760

In [265]:
test_sensor['Predict']=test_predict

In [266]:
test_sensor.head()

Depth_m                1.5    2.5    3.5    4.5    5.5    6.5    7.5    8.5  \
Date_Time                                                                     
2018-04-20 00:00:00  0.412  0.852  0.907  0.962  1.071  0.989  1.289  1.289   
2018-04-20 01:00:00  0.412  0.852  0.907  0.962  1.071  0.989  1.289  1.289   
2018-04-20 02:00:00  0.412  0.852  0.907  0.962  1.071  0.989  1.289  1.289   
2018-04-20 03:00:00  0.412  0.852  0.907  0.962  1.071  0.989  1.289  1.289   
2018-04-20 04:00:00  0.412  0.852  0.907  0.962  1.071  0.989  1.289  1.289   

Depth_m                9.5   11.5   12.5   14.5   16.5   18.5   20.5   Predict  
Date_Time                                                                       
2018-04-20 00:00:00  1.453  1.561  1.534  1.724  1.805  2.155  2.503  1.472845  
2018-04-20 01:00:00  1.453  1.561  1.534  1.724  1.805  2.155  2.503  1.472845  
2018-04-20 02:00:00  1.453  1.561  1.534  1.724  1.778  2.155  2.503  1.472587  
2018-04-20 03:00:00  1.453  1.561  1.534  1.724  1.778  2.155  2.503  1.472587  
2018-04-20 04:00:00  1.453  1.561  1.534  1.724  1.778  2.155  2.503  1.472587

In [267]:
test_prediction = test_sensor[['Predict']]
test_prediction.head()

Depth_m               Predict
Date_Time                    
2018-04-20 00:00:00  1.472845
2018-04-20 01:00:00  1.472845
2018-04-20 02:00:00  1.472587
2018-04-20 03:00:00  1.472587
2018-04-20 04:00:00  1.472587

In [268]:
test_prediction=test_prediction.rename(columns={"Predict": "Water_Temp_C"}).reset_index()

In [269]:
test_prediction.head()

Depth_m            Date_Time  Water_Temp_C
0        2018-04-20 00:00:00      1.472845
1        2018-04-20 01:00:00      1.472845
2        2018-04-20 02:00:00      1.472587
3        2018-04-20 03:00:00      1.472587
4        2018-04-20 04:00:00      1.472587

In [270]:
test_prediction.shape

(8760, 2)

In [271]:
test_prediction.to_csv(r'Trout_Prediction_d2.csv', index = False, header=True)


#### Ridge (best score up to now)

In [27]:
from sklearn.linear_model import Ridge
scores = []
for this_alpha in [1e-8,1,5,10,100,200,500]:  # By setting alpha close to 0, `Ridge` behaves similar as `LinearRegression`.
    
    linridge = Ridge(alpha = this_alpha)
    linridge.fit(X_poly, y)
    #r2_train = linridge.score(X_train_scaled, y_train)  # %%% Your code: get r2_train by the linridge.score on training data
    r2_test = linridge.score(X_poly, y)
    scores.append(r2_test)
scores
    

[0.998445368147906,
 0.9965134289386002,
 0.9958916045510641,
 0.9956191619067618,
 0.9939018867279208,
 0.9927734928507668,
 0.9906735208165726]

In [80]:
from sklearn.linear_model import Ridge
linridge = Ridge(alpha=0.005).fit(X_poly, y)

In [81]:
linridge.score(X_poly, y)

0.9970210090589776

#linridge.score(X_test_scaled, y_test)

In [82]:
y_pred_r = linridge.predict(test_poly)
y_pred_r

array([[1.40256512],
       [1.40256512],
       [1.40103041],
       ...,
       [3.58322175],
       [3.58470577],
       [3.55644243]])

array([[1.48712717],
       [1.48712717],
       [1.48365151],
       ...,
       [3.60906095],
       [3.60918791],
       [3.59701334]])

In [225]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred_r)

0.09349504711053618

In [83]:
test_sensor['Water_Temp_C']=y_pred_r

In [84]:
test_prediction = test_sensor[['Water_Temp_C']]
test_prediction=test_prediction.reset_index()

In [85]:
test_prediction.head()

Depth_m            Date_Time  Water_Temp_C
0        2018-04-20 00:00:00      1.402565
1        2018-04-20 01:00:00      1.402565
2        2018-04-20 02:00:00      1.401030
3        2018-04-20 03:00:00      1.401030
4        2018-04-20 04:00:00      1.401030

In [86]:
test_prediction.to_csv(r'Trout_Prediction_d3_0005.csv', index = False, header=True)

Lasso

In [111]:
from sklearn.linear_model import Lasso
lasso = Lasso().fit(X_poly, y)

In [112]:
lasso.score(X_poly, y)

0.0

In [228]:
lasso.score(X_test_scaled, y_test)

-3.028086815959341e-05

In [113]:
y_pred_l = lasso.predict(test_poly)
y_pred_l

array([5.06233878, 5.06233878, 5.06233878, ..., 5.06233878, 5.06233878,
       5.06233878])

https://scikit-learn.org/stable/modules/svm.html

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html

In [48]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression().fit(X_poly, y)
linreg.score(X_poly, y)

0.9976931829841948

In [273]:
linreg.score(X_test_scaled, y_test)

0.9908624468936779

In [49]:
y_pred_li = linreg.predict(test_poly)

In [50]:
y_pred_li

array([[1.38626942],
       [1.38626942],
       [1.37477246],
       ...,
       [3.58135436],
       [3.58048173],
       [3.56865624]])

In [51]:
test_sensor['Water_Temp_C']=y_pred_li

In [52]:
test_prediction = test_sensor[['Water_Temp_C']]
test_prediction=test_prediction.reset_index()

In [53]:
test_prediction.head()

Depth_m            Date_Time  Water_Temp_C
0        2018-04-20 00:00:00      1.386269
1        2018-04-20 01:00:00      1.386269
2        2018-04-20 02:00:00      1.374772
3        2018-04-20 03:00:00      1.374772
4        2018-04-20 04:00:00      1.374772

In [54]:
test_prediction.to_csv(r'Trout_Prediction_d3_l.csv', index = False, header=True)